allMarks = []
student1 = input("Enter the name of this student: ")
student1Marks = int(input(f"Enter the marks of {student1}: "))
allMarks.append(student1Marks)
student2 = input("Enter the name of this student: ")
student2Marks = int(input(f"Enter the marks of {student2}: "))
allMarks.append(student2Marks)
student3 = input("Enter the name of this student: ")
student3Marks = int(input(f"Enter the marks of {student3}: "))
allMarks.append(student3Marks)
student4 = input("Enter the name of this student: ")
student4Marks = int(input(f"Enter the marks of {student4}: "))
allMarks.append(student4Marks)
student5 = input("Enter the name of this student: ")
student5Marks = int(input(f"Enter the marks of {student5}: "))
allMarks.append(student5Marks)
student6 = input("Enter the name of this student: ")
student6Marks = int(input(f"Enter the marks of {student6}: "))
allMarks.append(student6Marks)
student7 = input("Enter the name of this student: ")
student7Marks = int(input(f"Enter the marks of {student7}: "))
allMarks.append(student7Marks)
allMarks.sort()
print(allMarks)

# studentMarks = int(input("Enter the marks: ")).split(",")
