friends = {}

inputUser = input("Enter your name: ")
inputLang = input(f"{inputUser}, Enter your Favorite Language: ")
friends.update({inputUser: inputLang})
inputUser = input("Enter your name: ")
inputLang = input(f"{inputUser}, Enter your Favorite Language: ")
friends.update({inputUser: inputLang})
inputUser = input("Enter your name: ")
inputLang = input(f"{inputUser}, Enter your Favorite Language: ")
friends.update({inputUser: inputLang})
inputUser = input("Enter your name: ")
inputLang = input(f"{inputUser}, Enter your Favorite Language: ")
friends.update({inputUser: inputLang})
print(friends)
