inputEight = set()

inputUser = int(input("Enter the number: "))
inputEight.add(inputUser)
inputUser = int(input("Enter the number: "))
inputEight.add(inputUser)
inputUser = int(input("Enter the number: "))
inputEight.add(inputUser)
inputUser = int(input("Enter the number: "))
inputEight.add(inputUser)
inputUser = int(input("Enter the number: "))
inputEight.add(inputUser)
inputUser = int(input("Enter the number: "))
inputEight.add(inputUser)
inputUser = int(input("Enter the number: "))
inputEight.add(inputUser)
inputUser = int(input("Enter the number: "))
inputEight.add(inputUser)
inputUser = int(input("Enter the number: "))
inputEight.add(inputUser)

print(inputEight)
