inputEight = set()

inputUser = input("Enter the number: ")
inputEight.add(inputUser)
inputUser = input("Enter the number: ")
inputEight.add(inputUser)
inputUser = input("Enter the number: ")
inputEight.add(inputUser)
inputUser = input("Enter the number: ")
inputEight.add(inputUser)
inputUser = input("Enter the number: ")
inputEight.add(inputUser)
inputUser = input("Enter the number: ")
inputEight.add(inputUser)
inputUser = input("Enter the number: ")
inputEight.add(inputUser)
inputUser = input("Enter the number: ")
inputEight.add(inputUser)
inputUser = input("Enter the number: ")
inputEight.add(inputUser)

print(inputEight)
